name: Version Check
author: Federico Grandi
description: An action that allows you to check whether your npm package version has been updated

inputs:
  diff-search:
    description: Whether to search the bump commit using diffs (recommended ONLY if not using standard 'npm version' commits)
    required: false
  file-name:
    description: A custom path to the package.json file
    required: false
  token:
    description: A GitHub token to use when running on private repos
    required: false

outputs:
  changed:
    description: Whether the version has changed in the examined commits
  type:
    description: The type of version change, if detectable (e.g. 'patch')
  version:
    description: The detected version number

runs:
  using: node12
  main: "lib/main.js"

branding:
  icon: package
  color: green
