name: Auto-publish
on: push

jobs:
  build:
    ... # If your package needs to be built, you can put that process here, so that it stays constantly updated

  publish:
    name: Publish to NPM & GitHub Package Registry
    runs-on: ubuntu-latest
    if: contains(github.ref, 'master') # Publish it only if the push comes from the master branch
    needs: build # We need to wait for the build to be committed before publishing

    steps:
      - name: Checkout repository
      uses: actions/checkout@v1.0.0
      with:
        ref: master

    - name: Check version changes
      uses: EndBug/version-check@v1.0.0
      id: check

    - name: Version update detected
      if: steps.check.outputs.changed == 'true'
      run: 'echo "Version change! -> ${{ steps.check.outputs.type }}"'

    - name: Set up Node.js for NPM
      if: steps.check.outputs.changed == 'true'
      uses: actions/setup-node@v1.2.0
      with:
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      if: steps.check.outputs.changed == 'true'
      run: npm install

    - name: Publish package to NPM
      if: steps.check.outputs.changed == 'true'
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Set up Node.js for GPR
      if: steps.check.outputs.changed == 'true'
      uses: actions/setup-node@v1.2.0
      with:
        registry-url: 'https://npm.pkg.github.com/'
        scope: '@endbug'

    - name: Set up package for GPR # You need to make sure you package name has the scope needed for GPR
      if: steps.check.outputs.changed == 'true'
      run: npm run gpr-setup

    - name: Publish package to GPR
      if: steps.check.outputs.changed == 'true'
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
