name: 'Handle stale issues and PRs'
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue is being marked as "stale" because it has been open 20 days with no activity. Remove the "stale" label or comment, otherwise this will be closed in 5 days.'
          stale-issue-label: 'status: stale'
          exempt-issue-labels: 'status: pinned'
          stale-pr-message: 'This PR is being marked as "stale" because it has been open 20 days with no activity. Remove the "stale" label or comment, otherwise this will be closed in 5 days.'
          stale-pr-label: 'status: stale'
          exempt-pr-labels: 'status: pinned'
          days-before-stale: 20
          days-before-close: 5
